name: Terraform Deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug paths
        run: |
          pwd
          ls -la
          ls -la infra || true
          ls -la infra/modules || true
          find infra/modules -maxdepth 2 -type f | head -n 50 || true

      - name: Debug module sources
        run: |
          sed -n '1,140p' infra/main.tf


      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

            - name: Terraform init
        run: terraform -chdir=infra init

      - name: Terraform fmt + validate
        run: |
          terraform -chdir=infra fmt -recursive
          terraform -chdir=infra validate

      - name: Terraform plan
        env:
          TF_VAR_image_tag: ${{ github.sha }}
          TF_VAR_acm_certificate_arn: ${{ secrets.TF_VAR_acm_certificate_arn }}
          TF_VAR_app_secret: ${{ secrets.TF_VAR_app_secret }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
        run: terraform -chdir=infra plan -out=tfplan -input=false

      - name: Terraform apply
        env:
          TF_VAR_image_tag: ${{ github.sha }}
         TF_VAR_acm_certificate_arn: ${{ secrets.TF_VAR_acm_certificate_arn }}
          TF_VAR_app_secret: ${{ secrets.TF_VAR_app_secret }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
       run: terraform -chdir=infra apply -auto-approve -input=false tfplan


      - name: Post-deploy health check
        run: |
          sleep 20
          curl -fsS https://tm.mhecsproject.com/health

